version: '3'
services:
  web:
    build: .
    command: flask run --host=0.0.0.0 --port=80
    ports:
      - "80:80"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development  # Utilise 'production' pour un environnement de production
    restart: always
